# Workflow for the CyStat's results

# Whenever pull request is made targeting branch initialisation, csv is reset
name: cystat

# Workflow's description
run-name: CyStat's results

# Function to schedule the time (UTC), day, month, and year of the workflow process
on:
  schedule:
    - cron: "03 10 * * 4" #UTC time and weekday (Thursday)

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    steps:
      # It checks out the latest content of your repository
      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: Upgrade pip
        run: pip install --upgrade pip
      # Installs the required Python dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          pip install -r requirements.txt
          pip install python-docx
          pip install babel
      
      - name: Run CyStat.py
        run: |
          python CyStat/CyStat.py
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "CyStat's results completed"
          git push origin HEAD:main
