name: check-urls

# Scraping description
run-name: Check Urls whether are accessible

on:
  schedule:
    - cron: '00 08 * * *'  # Runs at 00:00 UTC every day

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
      # It checks out the latest content of your repository
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        with:
          fetch-depth: 0
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: Upgrade pip
        run: pip install --upgrade pip
      # Installs the required Python dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
      - name: execute py script urls
        run: |
          python ScrapingCodes/urls.py
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "JOHN"
          git push origin HEAD:main
