# Code needed for the scraping process

# Whenever pull request is made targeting branch initialise, csv is reset
name: web-scraping

# Scraping description
run-name: Adding today's scraped data into raw_data.csv

# Function to add time,day, month to the scraping process
on:
  schedule:
    - cron: "45 17 * * *" #UTC time

jobs:
  getdataandrefreshmap:
    runs-on: ubuntu-latest
    steps:
      # It checks out the latest content of your repository
      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #install the python needed
      - name: Upgrade pip
        run: pip install --upgrade pip
      # Installs the required Python dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
      - name: Run WebScraping.py
        run: |
          python PythonCodes/WebScraping.py
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "scraping completed"
          git push origin HEAD:main
